name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate stats
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=WasteLLHero&show_icons=true&theme=radical&count_private=true&include_all_commits=true&access_token=${{ secrets.STATS_TOKEN }}" \
            -o stats.svg

      - name: Save as artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-stats
          path: stats.svg
