name: Generate GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # <- это важно для пуша

      - name: Generate stats
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=WasteLLHero&show_icons=true&theme=radical&count_private=true&include_all_commits=true&access_token=${{ secrets.STATS_TOKEN }}" \
            -o stats.svg

      - name: Commit and push
        run: |
          git config user.name "WasteLLHero"
          git config user.email "wastellhero@gmail.com"
          git add stats.svg
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
